### ISSUE TITLE
What about getting stream_run into the core?

### ISSUE THREAD

**Issue by eskaaren** [RexOps/rex-recipes#17]
It can be very useful to be able to print continuously from a long running task and this feels like it should be in core rather than a recipe?

**Comment by eskaaren** [comment]
Since in my case I had to set $| in the external script the same thing could also be done with:

``` perl
open(FH, "perl myscript.pl |");
while (<FH>) {
  Rex::Logger::info($_);
}
```

Perhaps it would be easy to implement something like that as an option for the already present run command?

**Comment by ferki** [comment]
An option for the `run` command sounds like a good idea :+1:

**Comment by eskaaren** [comment]
In fact what I suggested was possible to implement for local connections so I submitted a patch for that.
