### ISSUE TITLE
move the recipes into a more useful namespace.

### ISSUE THREAD

**Issue by SvenDowideit** [RexOps/rex-recipes#2]
I think the recipes should move into the Rex:: namespace.

firstly, so they won't conflict with non-rex perl modules that might be used - or worse, future CPAN modules that come into existance and then clash.

and secondly, so that when one of them becomes important enough to migrate into rex itself, no-one's code needs to change.

**Comment by krimdomu** [comment]
Yes, your right. I didn't wanted everywhere the "Rex::" thing. But it is really better to use the namespace in the right way.

So i will migrate all recipes.

**Comment by krimdomu** [comment]
moved them into new namespace
