### ISSUE TITLE
Add module to easily setup and run Sparrow checks

### ISSUE THREAD

**Issue by ferki** [RexOps/rex-recipes#27]
@melezhik on #26 provided a great example rex module to setup, configure and run a sparrow plugin on remote hosts. During our IRC discussions, we decided to aim for a more general approach due to high number of sparrow plugins (i.e. writing and maintaining a separate rex module for _each_ sparrow plugin does not scale).

The idea is to have a single `Rex::Misc::Sparrow` module which can handle setup/configuration of a list of Sparrow plugins provided via a config file for the task (standard CMDB and/or custom file).

Basic usage examples for the idea:
- setting up everything: `rex Misc:Sparrow:setup`
- running all checks: `rex Misc:Sparrow:check`

Extended ideas (to be done at a later point):
- run some checks, but not all: `rex Misc:Sparrow:check --plugins=check1,check2`
- run all checks except some: `rex Misc:Sparrow:check --except=check1,check2`

**Comment by melezhik** [comment]
Sounds good. My considerations. I'd rather talk about sparrow checkpoints,  not sparrow plugins.
Sparrow checkpoints are abstraction for runnable sparrow test suites , checkpoint consists of 3 components:
- **project** . Project group together logically related plugins . F.e. project_name = 'system' - system related plugins, project_name = 'webservers' - web servers related plugins. so on
- **checkpoint_name** - name of check point , pair (project_name, checkpoint_name) should be unique. For example project_name = system, checkpoint name = disk ; project_name = webservers, checkpoint name = nginx. so on
- **plugin name** - name of sparrow plugin   

Available plugins could be found at https://sparrowhub.org/search or by running `sparrow plg search` command.

So we would rather better have: 

```
rex Misc:Sparrow:run --checkpoints='system.disk,webservers.nginx' # run explicitly these checkpoints  
rex Misc:Sparrow:run --checkpoints='except  system.*' # run all  beside system checkpoints
rex Misc:Sparrow:run --checkpoints='except  system.disk* # run all beside system.disk checkpoint
rex Misc:Sparrow:run --checkpoints='system.* # run all system checkpoints 
```

This is like suggestion, we need to discuss ...

So, as for mentioned rex tasks:

Misc:Sparrow:setup will
- Install Sparrow ( this is cpan module )

```
cpanm Sparrow
```
- Install sparrow plugin(s) , f.e.

```
   sparrow plg install df-check
```
- Setup sparrow plguin(s)  

Setup sparrow plugin will:
-  create a sparrow projects, checkpoint(s) - is abstraction for runnable sparrow test suites , f.e.

```
     sparrow  project create  system 
     sparrow  check add system disk
     sparrow  check set system disk df-check 
```
-  generate suite.ini file  
- bind a checkpoint to a generated suite.ini file , f.e.

```
     sparrow check load_ini system disk /path/to/suite.ini/file
```

Some plugins do not require suite.ini files, so last two steps could be skipped.

Misc:Sparrow:check will
- run a sparrow checkpoint(s). F.e.

```
    sparrow check run disk system 
```

Sparrow entities to be defined at rex side:
- plugins list: 

Available plugins could be found at https://sparrowhub.org/search or by `sparrow plg search` command. F.e.

```
plugins_list:
 - df-check
 - nginx-check

```
- checkpoints list. Should be sparrow checkpoints list. F.e.

```
 checkpoints: 
 - project: system
   checkname : disk
   plugin: df-check 

 - project: webservers
   checkname : nginx
   plugin: nginx-check 

```
- checkpoints settings list. Should it be host specific? Need to discuss. Example:

```
 settings: 
 - project: system
  checkname : disk
  host: foo-bar-baz
  settings: 
    - threshold: 50

```

Probably ( not sure ) checkpoint settings could be set dynamically in runtime?:

```
rex Misc:Sparrow:check --checkpoints=system.disk --system.disk.threshold=50
```

**Comment by melezhik** [comment]
as for the reference on sparrow checkpoints - https://github.com/melezhik/sparrow#create-checkpoints

**Comment by ferki** [comment]
The intiial version is now merged, feel free to take maintainership on the Rex::Misc::Sparrow module, as I originall only wished to provide a starting point for this idea and I think that's done ^^
